### ISSUE TITLE
How can I run codred-blend.py with a larger batch size?

### ISSUE THREAD

**Issue by MakiseKuurisu** [thunlp/CodRED#1]
Sincerely admire your outstanding contribution for this work! 
Yet there's several problems I've met when running codred-blend.py:
It seems that 2 different types of datasets(Intra-doc/Cross-doc) were mixed, so that samples were processed one by one. Would you please tell me how it should be modified that I can process larger batches? With batch size=1 setting, 1 epoch took me 6 hours..

**Comment by yaoyuanTHU** [comment]
Hi, thanks for contacting. The simplest way will be using multiple GPU cards to speed up (4 in our case).

**Comment by tonytan48** [comment]
> Hi, thanks for contacting. The simplest way will be using multiple GPU cards to speed up (4 in our case).

Thank for the info. I am wondering is it possible to increase per_gpu_train_batch_size to higher. My memory consumption is 10GB/32GB yet if I increase the batch size it will pop assertion error from collate function. len(batch) == 1

**Comment by MakiseKuurisu** [comment]
> 

Thank you for replying! I've modified the code to surpport larger batch size, but the max batch size for a single gpu(with 24GB memory) was still no more than 3. Is it normal ?
