### ISSUE TITLE
Evaluating on the test set

### ISSUE THREAD

**Issue by CKRE** [thunlp/CodRED#2]
Hi, seems the data released only contains train and dev data, could you give some instructions about when we could get the testing performance? Thanks

**Comment by yaoyuanTHU** [comment]
Hi, we are working on releasing the test evaluation on Codalab. However, it seems that the Codalab platform is fixing a problem in creating new competitions ([issue report](https://github.com/codalab/codalab-competitions/issues/3121)). We will release the test evaluation as soon as the problem get fixed. Thanks.

**Comment by yaoyuanTHU** [comment]
Hi, the evaluation on test set is available on [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/3770) now.
