### ISSUE TITLE
Progress on your mentioned competition for evaluation on test set and the release of the testset

### ISSUE THREAD

**Issue by Hyusheng** [thunlp/CodRED#3]
Thanks for your work on this task and the constructed dataset. But when will you release the testset?

**Comment by yaoyuanTHU** [comment]
Hi, thanks for the interest. We are planning to release the test set on CodaLab, which will be ready before March 15.

**Comment by yaoyuanTHU** [comment]
Hi, we are working on releasing the test evaluation on Codalab. However, it seems that the Codalab platform is fixing a problem in creating new competitions (https://github.com/codalab/codalab-competitions/issues/3121). We will release the test evaluation as soon as the problem get fixed. Thanks.

**Comment by Hyusheng** [comment]
Hi, Codalab seems to have fixed this bug. Can you try to upload the test set again? thanks!

**Comment by yaoyuanTHU** [comment]
Hi, the evaluation on test set is available on [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/3770) now.
